# The below approved services are based off the list located here: https://aws.amazon.com/compliance/hipaa-eligible-services-reference/
resource "aws_organizations_policy" "allow_hipaa_services" {
  name        = "Allow HIPAA Services"
  description = "Only allow HIPAA BAA compliant services as of 1/15/2021"

  content = <<CONTENT
{
  "Version": "2012-10-17",
  "Statement": [
    {
    "Effect": "Allow",
    "Action": [
      "a4b:*",
      "acm:*",
      "amplify:*",
      "apigateway:*",
      "appmesh:*",
      "appstream:*",
      "appsync:*",
      "athena:*",
      "autoscaling:*",
      "backup:*",
      "batch:*",
      "chime:*",
      "clouddirectory:*",
      "cloudformation:*",
      "cloudfront:*",
      "cloudhsm:*",
      "cloudtrail:*",
      "cloudwatch:*",
      "codebuild:*",
      "codecommit:*",
      "codedeploy:*",
      "codepipeline:*",
      "cognito-identity:*",
      "cognito-idp:*",
      "cognito-sync:*",
      "comprehend:*",
      "comprehendmedical:*",
      "config:*",
      "connect:*",
      "dataexchange:*",
      "datasync:*",
      "directconnect:*",
      "dms:*",
      "ds:*",
      "dynamodb:*",
      "ebs:*",
      "ec2:*",
      "ecr:*",
      "ecs:*",
      "eks:*",
      "elasticache:*",
      "elasticbeanstalk:*",
      "elasticfilesystem:*",
      "elasticloadbalancing:*",
      "elasticmapreduce:*",
      "es:*",
      "events:*",
      "firehose:*",
      "fms:*",
      "forecast:*",
      "freertos:*",
      "fsx:*",
      "glacier:*",
      "globalaccelerator:*",
      "glue:*",
      "greengrass:*",
      "guardduty:*",
      "healthlake:*",
      "importexport:*",
      "inspector:*",
      "iot:*",
      "iotevents:*",
      "kafka:*",
      "kendra:*",
      "kinesis:*",
      "kinesisanalytics:*",
      "kinesisvideo:*",
      "kms:*",
      "lakeformation:*",
      "lambda:*",
      "lex:*",
      "logs:*",
      "macie:*",
      "mediaconnect:*",
      "mediaconvert:*",
      "medialive:*",
      "mobiletargeting:*",
      "mq:*",
      "neptune-db:*",
      "opsworks-cm:*",
      "opsworks:*",
      "organizations:*",
      "outposts:*",
      "personalize:*",
      "polly:*",
      "qldb:*",
      "quicksight:*",
      "rds:*",
      "redshift:*",
      "rekognition:*",
      "robomaker:*",
      "route53:*",
      "s3:*",
      "sagemaker:*",
      "secretsmanager:*",
      "securityhub:*",
      "serverlessrepo:*",
      "servicecatalog:*",
      "servicediscovery:*",
      "ses:*",
      "shield:*",
      "sms:*",
      "snowball:*",
      "sns:*",
      "sqs:*",
      "ssm:*",
      "states:*",
      "storagegateway:*",
      "swf:*",
      "textract:*",
      "transcribe:*",
      "transfer:*",
      "translate:*",
      "waf:*",
      "workdocs:*",
      "worklink:*",
      "workspaces:*",
      "xray:*"
    ],
    "Resource": "*"
    }
  ]
}
CONTENT

}

resource "aws_organizations_policy_attachment" "allow_hipaa_services_attachment" {
  policy_id = aws_organizations_policy.allow_hipaa_services.id
  target_id = var.target_id
}

